# Generated by Django 5.1.2 on 2024-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_project_smmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="smmodel",
            name="aws_arn",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
