# Generated by Django 5.1.2 on 2024-10-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_smmodel_aws_arn"),
    ]

    operations = [
        migrations.AddField(
            model_name="smmodel",
            name="endpoint_config_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="smmodel",
            name="endpoint_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
