# Generated by Django 5.1.2 on 2024-10-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_smmodel_is_deployed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
